name: Get Aws Credentials

on:
  push:
    branches:
      - feat-37-ci-cd

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Get Aws Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::564499745731:role/github_actions_role
          aws-region: us-east-2
