name: Test flow

on:
  push:
    branches:
      - '*'
      - '!production'

      
jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: 변경된 파일 확인
        id: changed_files
        run: |
            FE_DIFF=$(git diff --name-only -- frontend)
            BE_DIFF=$(git diff --name-only -- backend)

            if [ -n $FE_DIFF ]; then
              echo FE_DIFF=true >> $GITHUB_ENV
            fi


            if [ -n "$BE_DIFF" ]; then
              echo BE_DIFF=true >> $GITHUB_ENV
            fi

      - name: github 확인
        run: |
          echo ${{env.FE_DIFF}}
          echo ${{env.BE_DIFF}}


      - name: frontend test
        if: ${{env.FE_DIFF == 'true'}}
        run: |
          echo fe diff!
      
      - name: backend test
        if: ${{ env.BE_DIFF == 'true' }}
        run: |
          echo fe diff!
      